make test:
	g++ -std=c++11 TestMain.cpp -o TestMain \
	-I../src \
	../src/KalmanFilter.cpp \
	../src/IMUInterface.cpp \
	../src/BarometerInterface.cpp \
	../src/RocketTracker.cpp \

make clean:
	rm TestMain