make test:
	g++ -std=c++11 TestMain.cpp -o TestMain \
	-I../src \
	../src/Matrix.hpp \
	../src/Types.hpp \
	../src/KalmanFilter.hpp \
	../src/KalmanFilter.cpp \
	../src/IMUInterface.hpp \
	../src/IMUInterface.cpp \
	TestMacros.hpp \
	TestMatrix.hpp \
	TestKalmanFilter.hpp \

make clean:
	rm TestMain